// test-output/vue/stroke/general/PiAtMarkStroke.vue
<template>
  <svg
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    xmlns="http://www.w3.org/2000/svg"
    :class="className"
    fill="none"
    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" :style="{color: color || 'currentColor'}"
    v-bind="$attrs"
  >
    
  </svg>
</template>

<script>
/**
 * PiAtMarkStroke icon from the stroke style in general category.
 */
export default {
  name: 'PiAtMarkStroke',
  props: {
    size: {
      type: Number,
      default: 24
    },
    color: {
      type: String,
      default: undefined
    },
    className: {
      type: String,
      default: undefined
    }
  }
}
</script>

// test-output/react-tsx/stroke/general/PiAtMarkStroke.tsx
import React from 'react';

/**
 * PiAtMarkStroke icon from the stroke style in general category.
 */
interface PiAtMarkStrokeProps extends React.SVGProps<SVGSVGElement> {
  size?: number;
  color?: string;
  className?: string;
}

export default function PiAtMarkStroke({
  size = 24,
  color,
  className,
  ...props
}: PiAtMarkStrokeProps): JSX.Element {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      fill="none"
      stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style={{color: color || "currentColor"}}
      
      {...props}
    >
      
    </svg>
  );
}
